export const glossary = [
  ['Allometry · allométrie', 'How one biological measurement scales with another, such as brain mass with body mass.'],
  ['Alloparental care · soins alloparentaux', 'Care provided by individuals other than the parents.'],
  ['Basal metabolism · métabolisme basal', 'Expenditure measured at rest under standard fasting and thermal conditions; not all daily expenditure.'],
  ['Carrying capacity · capacité porteuse', 'The population an environment can support under specified ecological and technological conditions.'],
  ['Cost of transport · coût de transport', 'Energy used per distance, often normalised by body mass; different from power.'],
  ['Dental calculus · tartre dentaire', 'Mineralised plaque that can preserve residues, with contamination and interpretation requiring checks.'],
  ['Diagenesis · diagenèse', 'Changes after burial that can affect preservation and chemical signals.'],
  ['Doubly labelled water · eau doublement marquée', 'An isotope method for estimating expenditure over time from water and carbon-dioxide turnover.'],
  ['Ecological inheritance · héritage écologique', 'Environmental conditions left by earlier generations.'],
  ['Encephalization · encéphalisation', 'Relative brain enlargement, evaluated using an explicit comparative baseline.'],
  ['Endocast · moulage endocrânien', 'A cast or digital reconstruction of the braincase interior; not a preserved brain.'],
  ['Endothermy · endothermie', 'Substantial internal heat production through metabolism.'],
  ['Fallback food · aliment de repli', 'A resource relied on when preferred foods are scarce; it can strongly influence functional anatomy.'],
  ['Hominin · hominine', 'A member of the human lineage after its divergence from the chimpanzee lineage, including extinct related branches.'],
  ['Homeothermy · homéothermie', 'Maintenance of a relatively stable body temperature.'],
  ['Isotope · isotope', 'A form of an element with a particular number of neutrons. Stable isotope ratios can trace processes.'],
  ['Lactase persistence · persistance de la lactase', 'Continued substantial activity of the lactose-digesting enzyme into adulthood.'],
  ['Life history · histoire de vie', 'The timing and pattern of growth, reproduction, investment, survival and longevity.'],
  ['Metabolizable intake · apport métabolisable', 'Food energy available after digestive losses.'],
  ['Microwear · micro-usure', 'Microscopic pits and scratches reflecting recent tooth use and food processing.'],
  ['Niche construction · construction de niche', 'Modification of environmental conditions by organisms, with possible ecological and evolutionary consequences.'],
  ['Per mille · pour mille', 'Parts per thousand (‰), used for small isotope-ratio differences; not percent.'],
  ['Phylogeny · phylogénie', 'Evolutionary relationships, usually represented as a branching tree with explicit uncertainty.'],
  ['Power · puissance', 'Energy per unit time, measured in watts (joules per second).'],
  ['Taphonomy · taphonomie', 'Processes between death and discovery, including deposition, preservation and recovery.'],
  ['Thermic effect of food · effet thermique des aliments', 'Expenditure associated with processing and assimilating food.'],
  ['Throughput · flux énergétique', 'The amount of energy acquired and processed over time; it need not be fixed across species.'],
  ['Weaning · sevrage', 'The transition away from breast milk, which need not imply independent food acquisition.']
];
