export interface Question { prompt: string; options: string[]; correct: number; explanation: string }
export const questions: Record<string, Question> = {
  'budget': { prompt: 'A body uses 1,600 kcal at rest, including 320 kcal for its brain, plus 600 kcal for activity and 200 kcal for digestion. What is its total?', options: ['2,400 kcal', '2,720 kcal', '1,920 kcal'], correct: 0, explanation: '2,400 kcal. The 320 kcal brain cost is already included in the resting expenditure. Adding it again would count the same expenditure twice.' },
  'menopause': { prompt: 'What does the 2023 Ngogo finding establish?', options: ['Every chimpanzee community has a long post-reproductive life', 'Substantial post-reproductive survival and menopause occur in at least one wild chimpanzee community', 'The grandmother hypothesis has been proved'], correct: 1, explanation: 'The demographic and hormonal observations concern the Ngogo community. They revise a categorical human–chimpanzee contrast, while leaving the distribution and evolutionary explanation open.' },
  'brain': { prompt: 'A newborn’s brain is a small fraction of its eventual adult size. What follows from this observation alone?', options: ['The baby was born prematurely', 'Most neural development must happen after birth', 'Substantial brain enlargement remains; maturity needs other measures'], correct: 2, explanation: 'A ratio combines neonatal and adult size. A large adult denominator can create a low ratio. It cannot by itself date neural events or establish premature birth.' },
  'tooth': { prompt: 'A juvenile fossil has some slow-forming teeth and some more rapidly developing ones. Which conclusion is strongest?', options: ['It had a fully modern human childhood', 'Its development was mosaic; different traits changed at different times', 'It had no social care'], correct: 1, explanation: 'Different developmental traits need not move together. Teeth constrain a growth history, but they do not directly measure all brain development, dependency or care.' },
  'diet': { prompt: 'High collagen nitrogen isotope values and plant residues occur in the same population. Must one observation be wrong?', options: ['Yes: high nitrogen means every calorie came from meat', 'No: collagen mainly reflects dietary protein, and residues record another part of food use', 'Yes: residues measure the percentage of calories from plants'], correct: 1, explanation: 'The proxies record different aspects and time windows of diet. Neither directly provides the complete caloric menu. Both can be consistent with substantial animal protein and some plant consumption.' },
  'fire': { prompt: 'A site preserves strong evidence of deliberate fire-making about 400,000 years ago. What does it establish?', options: ['Fire-making was invented precisely then', 'Every group already depended on cooking', 'Deliberate ignition was possible in that context by that time'], correct: 2, explanation: 'An archaeological occurrence establishes a minimum antiquity within its context. It does not identify the first invention or the frequency and necessity of use elsewhere.' },
  'gait': { prompt: 'Walking costs less energy per kilometre than a comparison gait in a present-day experiment. What does this establish?', options: ['A measured energetic advantage under the experiment’s conditions', 'The unique reason bipedalism evolved', 'The exact cost of walking for every Australopithecus'], correct: 0, explanation: 'Present-day measurements establish a mechanism and a comparison. Inferring its role in selection requires independent evidence about ancestral anatomy, behaviour and environments.' },
  'clothing': { prompt: 'A site has no preserved eyed needles. Which conclusion is defensible?', options: ['Its occupants wore no clothes', 'The evidence does not establish eyed-needle sewing at this site; other clothing remains possible', 'They could not live in a cold climate'], correct: 1, explanation: 'Preservation, excavation and alternative technologies matter. Draped skins, awls, bindings or unpreserved implements can precede surviving eyed needles.' },
  'milk': { prompt: 'Milk residues predate high frequencies of lactase persistence. What does that change?', options: ['It rules out gene–culture feedback', 'It separates cultural milk use from the later genetic change that needs explanation', 'It means ancient people could not use milk'], correct: 1, explanation: 'Dairying can exist with fermentation, processing and individual variation. The timing and context of selection need evidence beyond the fact that milk was available.' },
  'synthesis': { prompt: 'Which new observation would best test an explanation of slow childhood based on energetic constraints?', options: ['Another drawing of an adult skull', 'Independent measurements of age-specific energy demand, growth and food transfers', 'A simulation whose rules already require slow childhood'], correct: 1, explanation: 'Independent measurements can challenge the proposed relationships. A model that assumes the conclusion only illustrates its assumptions.' }
};
