export const symposium = [
  { slug: 'the-expensive-brain-predictions-and-comparative-tests', speaker: 'Carel van Schaik', title: 'The Expensive Brain: Predictions and Comparative Tests', role: 'Energetic buffering and comparative tests · chapters 1–2', video: 'ooIjghG6FS0' },
  { slug: 'brain-energetics-and-the-evolution-of-human-childhood', speaker: 'Christopher Kuzawa', title: 'Brain Energetics and the Evolution of Human Childhood', role: 'Developmental demand · chapter 2', video: 'J48njNHiNSY' },
  { slug: 'growing-up-fast-but-maturing-slowly-uniquely-human-pattern-of-development', speaker: 'Philipp Gunz', title: 'Growing Up Fast but Maturing Slowly', role: 'Optional developmental comparison · chapter 2', video: 'vIiCN4njT4U' },
  { slug: 'born-to-walk-run-and-rest-the-evolution-of-locomotor-energetics-in-homo', speaker: 'Daniel Lieberman', title: 'Born to Walk, Run and Rest', role: 'Optional locomotor perspective · chapter 4', video: 'CPcFFvTmFeg' },
  { slug: 'reproductive-energetics-in-primates', speaker: 'Cécile Garcia', title: 'Reproductive Energetics in Primates', role: 'Optional reproductive comparison · chapter 1', video: 'oDH0jH2ljRs' },
  { slug: 'neandertal-energetic-ecology-reproduction-and-demography', speaker: 'Steven Churchill', title: 'Neandertal Energetic Ecology, Reproduction, and Demography', role: 'Optional synthesis case · chapters 1, 3 and 5', video: 'MhASkwCmBk0' },
  { slug: 'metabolic-acceleration-in-the-genus-homo-brains-babies-and-bipedalism', speaker: 'Herman Pontzer', title: 'Metabolic Acceleration in the Genus Homo', role: 'Expanded throughput · chapters 1–2', video: 'yKtiTsJp_3Y' },
  { slug: 'the-costs-of-fire', speaker: 'Amanda Henry', title: 'The Costs of Fire', role: 'Acquisition and preparation costs · chapter 3', video: 'FlORMGD6b7Y' },
  { slug: 'traces-of-fire-use-in-pleistocene-europe-patterns-and-interpretations', speaker: 'Wil Roebroeks', title: 'Traces of Fire Use in Pleistocene Europe', role: 'Not recorded; consult written fire research in the bibliography', video: null },
  { slug: 'the-intermittent-evidence-for-fire-in-neandertal-sites-means-they-were-not-obligate-fire-users', speaker: 'Shannon McPherron', title: 'Intermittent Evidence for Fire in Neandertal Sites', role: 'Optional evidence case · chapter 3; consider later ignition evidence', video: 'v5ukt4MG6zQ' },
  { slug: '40-years-of-investigation-on-ancient-hominin-diets-through-isotope-studies-limits-and-solutions', speaker: 'Klervia Jaouen', title: 'Ancient Hominin Diets through Isotope Studies: Limits and Solutions', role: 'Dietary inference and preservation · chapter 3', video: 'ocWk1gR3Lco' },
  { slug: 'partners-in-chyme-hominin-microbial-interactions-in-energy-acquisition', speaker: 'Rachel Carmody', title: 'Partners in Chyme', role: 'Optional microbial perspective · chapter 3', video: 'M6zVcPr-rrg' },
  { slug: 'energy-cost-and-gain-from-prey-acquisition-and-food-processing-during-the-palaeolithic', speaker: 'Camille Daujeard', title: 'Energy Cost and Gain from Prey Acquisition and Food Processing', role: 'Optional handling and transport evidence · chapter 3', video: 'yqeIl-LR-tk' },
  { slug: 'mitigating-the-metabolic-and-other-costs-of-largely-meat-based-neanderthal-diet', speaker: 'John Speth', title: 'Costs of a Largely Meat-Based Neanderthal Diet', role: 'Optional nutritional and fuel constraints · chapter 3', video: 'ADl9iMz_3yc' },
  { slug: 'coping-with-prey-seasonal-fluctuations-year-in-the-life-of-paleolithic-hunters', speaker: 'William Rendu', title: 'Coping with Prey Seasonal Fluctuations', role: 'Optional archaeological seasonality · chapter 3', video: 'ue-CdNTtCkI' }
];
